myApp/urls.py
from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
    path("",views.home, name='home'),
    path("about/",views.about, name='about'),
]

myProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("",include("myApp.urls")),
    path("posts/",include("post.urls")),
    path("users/", include("users.urls")),
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

post/urls.py
from django.urls import path
from . import views

app_name = "posts"

urlpatterns = [
    path('',views.post_list, name='list'),
    path('<slug:slug>', views.post_page, name="page")
]

users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('register/',views.user_list, name='register'),
]

post/models.py
from django.db import models

# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=100)
    body = models.TextField()
    slug = models.SlugField()
    date = models.DateTimeField(auto_now_add=True)
    banner = models.ImageField(default='fallback.png', blank=True)

    def __str__(self):
        return self.title

users/models.py
from django.db import models

# Create your models here.

myApp/views.py
from django.shortcuts import render
# from django.http import HttpResponse
from django.shortcuts import render
# Create your views here.

def home(request):
    # return HttpResponse("Hello")
    return render(request,'home.html')
def about(request):
    # return  HttpResponse("About Page")
    return render(request, "about.html")

post/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.
from .models import Post


def post_list(request):
    posts = Post.objects.all().order_by('-date')
    return  render(request,"posts/post_list.html",
                   {"posts":posts})

def post_page(request, slug):
    post = Post.objects.get(slug=slug)
    return render(request, "posts/post_page.html",
                  {"post": post})

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm

# Create your views here.
def user_list(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("posts:list")
    else:
        form = UserCreationForm()
    return render(request, "users/register.html", {"form":form})

post/templates/posts/post_list.html
{% extends 'layout.html'%}

{% block title %}
Posts List
{% endblock %}

{% block content %}
<section>
    <h1>Post Listss</h1>

    {% for post in posts %}
    <article class="post">
        <h2>
            <a href="{% url 'posts:page' slug=post.slug %}">
            {{post.title}}
        </a>
        </h2>
        <p>{{post.date}}</p>
        <p>{{post.body}}</p>
    </article>
    {% endfor %}
</section>

{% endblock %}

post/templates/posts/post_page.html
{% extends 'layout.html'%}

{% block title %}
{{post.title}}
{% endblock %}

{% block content %}
<section>
    <img
            class="banner"
            src="{{ post.banner.url }}"
    alt="{{ post.title }}">
    <h1>{{post.title}}</h1>
        <p>{{post.date}}</p>
        <p>{{post.body}}</p>

</section>
{% endblock %}

templates/about.html
{% extends 'layout.html'%}

{% block title %}
About
{% endblock %}

{% block content %}
<h1>About Page</h1>
<p>Check the <a href="/about">Home Page.</a> </p>
{% endblock %}

templates/home.html
{% extends 'layout.html'%}

{% block title %}
Home
{% endblock %}

{% block content %}
<h1>Home Page</h1>
<p>Check the <a href="/about">About Page.</a> </p>
{% endblock %}

templates/layout.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
        Django App
        {% endblock %}
    </title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <script src="{% static 'js/main.js' %}" defer></script>
</head>
<body>
<nav>
    <a href="/">
        <span role="img" aria-label="Home" title="Home">🏠</span></a>
    <a href="/about">
        <span role="img" aria-label="About">😀</span></a>
    <a href="{% url 'posts:list' %}">
        <span role="img" aria-label="Post">📰</span>
    </a>
    <a href="{% url 'users:register' %}">
        <span role="img" aria-label="User Registration">🚀</span></a>
</nav>
<main>
{% block content %}

{% endblock %}
    </main>
</body>
</html>

users/templates/users/register.html
{% extends 'layout.html'%}

{% block title %}
Register a New User
{% endblock %}

{% block content %}

<h1>Register a New User</h1>
<form class="form-with-validation"
      action="/users/register/" method="post">
    {% csrf_token %}
    {{ form }}
        <button class="form-submit">Submit</button>
</form>


{% endblock %}